version: '3'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    container_name: openborders
    command: bash -c "rm -f tmp/pids/server.pid && rake db:migrate RAILS_ENV=development && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db:
