# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Situation.create([
	{id: 0, title: 'Your president decides to bomb innocent civilians, in order to maintain power.'},
	{id: 1, title: 'A neighboring country decides to invade part of your country to improve their strategic position and/or access to fossile ressources.'},
	{id: 2, title: 'A member of your family was captured forcefully by the police and taken into custody for a crime he/she didn''t commit.'},
	{id: 3, title: 'A member of your family was captured forcefully by forces of the government and taken into custody for critical speech about them or the government.'},
	{id: 4, title: 'A new government rule prohibits drinking alcohol or smoking and is controlled strictly by armed forces. If they see you drinking or smoking, they will send you to jail. Unfortunately, you are (somewhat) addicted to alcohol and/or tabaco.'},
	{id: 5, title: 'The situation in your country is getting worse every day and your country is surrounded by water on most side and a country with a worse situation than in your own. You decide to flee to a neighboring country.'},
	{id: 6, title: 'A bomb detonated next to your neighbourhood. Luckily nobody in your family was harmed, but a friend of you living there died.'},
	{id: 7, title: 'Your wife/husband/partner has a different religion than yours which is now forbidden by the government. Practitioners of her religion are being hanged publicly and their whole family is under general suspicion to collaborate.'},
	{id: 8, title: 'You work as a police officer in your country and are forced by the government/by a dictator to question people through torture (waterboarding, sleep deprivation, abuse, ...) and you know exactly that these people are innocent. If you don''t follow the orders, you will be tortured instead.'},
	{id: 9, title: 'You, your wife and your three kids have to flee the country because you are wanted by your government for having sold alcohol. You have enough money to pay for two seets in a boat.'},
	{id: 10, title: 'You hide some friends of your family which believe in a religion prohibited by your government in your basement. Your neighbour knows about your situation. After a few weeks, you are being questioned by the police and they threaten you with years in jail, if you should hide some of these haunted/pursued people.'},
	{id: 11, title: 'You are a scientist at your local university. The new government tries to build more atom powered weapons. You''re spezialized? in this area and have to help them to create these weapons. Otherwise, you will being punished.'},
	{id: 12, title: 'Your son was imprisoned by forces of the government and taken into custody for critical speech about the government.'},
	{id: 13, title: 'You immigrated 20 years ago together with your wife and kids. The government has changed recently and is enacting drastic laws. According to the newest law, immigrants are not allowed to stay in the country but have to return to their home country. Your best friend is father to three small children. He lost his property and job. In order to earn money to buy food, he had to join the ruthless army of the government to enforce their laws.'},
	{id: 14, title: 'You work for the government to brutally enforce their laws. One of your oldest friends has repeatedly sold cigarettes publicly on the streets, which is prohibited. He has been interrogated and imprisoned before for the same crime and the government looses patience. You have the order to imprison and publicly crucifix him.'},
	])

Question.create([
	{id: 0, situation_id: 2, text: 'What do you do?'},
	{id: 1, situation_id: 4, text: 'What do you do?'},
	{id: 2, situation_id: 5, text: 'You try to flee via ...'},
	{id: 3, situation_id: 6, text: 'How do you react?'},
	{id: 4, situation_id: 7, text: 'What do you do?'},
	{id: 5, situation_id: 8, text: 'How do you behave?'},
	{id: 6, situation_id: 9, text: 'What will you do?'},
	{id: 7, situation_id: 10, text: 'How do you react?'},
	{id: 8, situation_id: 11, text: 'How do you react?'},
	{id: 9, situation_id: 12, text: 'What do you do?'},
	{id: 10, situation_id: 13, text: 'How do you react?'},
	{id: 11, situation_id: 14, text: 'What will you do?'},
	])

Answer.create([
	{question_id: 0, text: 'You go to the police and try to explain that he/she did nothing wrong.'},
	{question_id: 0, text: 'Out of fear of getting punished, you take no action.'},
	{question_id: 1, text: 'You are continuing smoking/drinking and try to do it in secret places.' },
	{question_id: 1, text: 'You stop smoking/drinking and adjust to the new rules.' },
	{question_id: 2, text: 'boat' },
	{question_id: 2, text: 'public transportation' },
	{question_id: 2, text: 'on foot' },
	{question_id: 3, text: 'You take action and try to flee.' },
	{question_id: 3, text: 'You decide to stay in your country. You demonstrate your decision by burying your friend.' },
	{question_id: 4, text: 'You help her hiding her religion and risk being hanged as well.' },
	{question_id: 4, text: 'You tell the government about her to save yourself.' },
	{question_id: 5, text: 'You try to let some people escape.' },
	{question_id: 5, text: 'You refuse to take action in these tortures.' },
	{question_id: 5, text: 'You follow the orders, but try to mitigate your tortures.' },
	{question_id: 5, text: 'You follow the orders and are happy to do so.' },
	{question_id: 6, text: 'You try to hide and wait until you have enough money in several months risking being captured every day.' },
	{question_id: 6, text: 'You buy two seats for two of your kids.' },
	{question_id: 6, text: 'You buy two seats for you and your wife.' },
	{question_id: 6, text: 'You buy a seat for you and one of your kids.' },
	{question_id: 6, text: 'You buy a seat for your wife and one of your kids.' },
	{question_id: 7, text: 'You deny hiding your friends.' },
	{question_id: 7, text: 'You give hints to the police where your friends are hiding in your house.' },
	{question_id: 8, text: 'You help them building mass destruction weapons against your will.' },
	{question_id: 8, text: 'You help them building mass destruction weapons, which was on your mind anyway.' },
	{question_id: 8, text: 'You refuse to help them.' },
	{question_id: 9, text: 'You stay calm and quiet and accept the superiour government.' },
	{question_id: 9, text: 'You contact officials of the government and ask them to release your son. Chances are very low, that you are heard and even if that your son is released again. He is a danger to the stability of their power.' },
	{question_id: 9, text: 'You critize the government in conversations to friends and family in secret. You trust them, but you have to live in constant fear that one of the persons you talk to betrays you for a sack of money.' },
	{question_id: 9, text: 'You publicly speak against the government and thereby accept following your son into prison. Your wife has to care for the other kids alone. There are not many possibilities to earn money.' },
	{question_id: 10, text: 'You try to hide and try to convince him to leave the forces and to look for another job. Although chances are almost non-existent. Also, the government will interrogate him before he can leave the forces as they suspect him to being involved with the "enemies of the country". They will try to convince him to stay by publicly denouncing him, prohibiting him to find a new job.' },
	{question_id: 10, text: 'You try to hide and to convince him that you should be allowed to stay in the country. However, if he receives the order to force you out of the country he most likely will do whatever is best for his family.' },
	{question_id: 10, text: 'You try to hide and hope that he will not tell the government about you still being in the country.' },
	{question_id: 10, text: 'You stop the contact to him and hide somewhere else.' },
	{question_id: 10, text: 'You leave the country.' },
	{question_id: 11, text: 'You tell your friend to hide. When the government asks you about him you tell them that he was hiding. You risk being suspected to have helped him. This may be to your and your family''s disadvantage in the future.' },
	{question_id: 11, text: 'You imprison your friend and tell him that it is his own fault. You also tell this to his wife and little daughter.' },
	])

Survey.create([
	{id: 0, title: 'Tolerance', text: 'TODO'},
	])

SurveyHasSituation.create([
	{survey_id: 0, situation_id: 0},
	{survey_id: 0, situation_id: 1},
	{survey_id: 0, situation_id: 2},
	{survey_id: 0, situation_id: 3},
	{survey_id: 0, situation_id: 4},
	{survey_id: 0, situation_id: 5},
	{survey_id: 0, situation_id: 6},
	{survey_id: 0, situation_id: 7},
	{survey_id: 0, situation_id: 8},
	{survey_id: 0, situation_id: 9},
	{survey_id: 0, situation_id: 10},
	{survey_id: 0, situation_id: 11},
	{survey_id: 0, situation_id: 12},
	{survey_id: 0, situation_id: 13},
	{survey_id: 0, situation_id: 14},
	])

Nationality.create([
{name: 'Afghan', continent_id: 4},
{name: 'Albanian', continent_id: 3},
{name: 'Algerian', continent_id: 5},
{name: 'American', continent_id: 2},
{name: 'Andorran', continent_id: 3},
{name: 'Angolan', continent_id: 5},
{name: 'Antiguans', continent_id: 2},
{name: 'Argentinean', continent_id: 0},
{name: 'Armenian', continent_id: 3},
{name: 'Australian', continent_id: 1},
{name: 'Austrian', continent_id: 3},
{name: 'Azerbaijani', continent_id: 3},
{name: 'Bahamian', continent_id: 2},
{name: 'Bahraini', continent_id: 4},
{name: 'Bangladeshi', continent_id: 4},
{name: 'Barbadian', continent_id: 2},
{name: 'Barbudans', continent_id: 2},
{name: 'Batswana', continent_id: 5},
{name: 'Belarusian', continent_id: 3},
{name: 'Belgian', continent_id: 3},
{name: 'Belizean', continent_id: 2},
{name: 'Beninese', continent_id: 5},
{name: 'Bhutanese', continent_id: 4},
{name: 'Bolivian', continent_id: 0},
{name: 'Bosnian', continent_id: 3},
{name: 'Brazilian', continent_id: 0},
{name: 'British', continent_id: 3},
{name: 'Bruneian', continent_id: 4},
{name: 'Bulgarian', continent_id: 3},
{name: 'Burkinabe', continent_id: 5},
{name: 'Burmese', continent_id: 4},
{name: 'Burundian', continent_id: 5},
{name: 'Cambodian', continent_id: 4},
{name: 'Cameroonian', continent_id: 5},
{name: 'Canadian', continent_id: 2},
{name: 'Cape Verdean', continent_id: 5},
{name: 'Central African', continent_id: 5},
{name: 'Chadian', continent_id: 5},
{name: 'Chilean', continent_id: 0},
{name: 'Chinese', continent_id: 4},
{name: 'Colombian', continent_id: 0},
{name: 'Comoran', continent_id: 5},
{name: 'Congolese', continent_id: 5},
{name: 'Costa Rican', continent_id: 2},
{name: 'Croatian', continent_id: 3},
{name: 'Cuban', continent_id: 2},
{name: 'Cypriot', continent_id: 3},
{name: 'Czech', continent_id: 3},
{name: 'Danish', continent_id: 3},
{name: 'Djibouti', continent_id: 5},
{name: 'Dominican', continent_id: 2},
{name: 'Dutch', continent_id: 3},
{name: 'East Timorese', continent_id: 4},
{name: 'Ecuadorean', continent_id: 0},
{name: 'Egyptian', continent_id: 5},
{name: 'Emirian', continent_id: 4},
{name: 'Equatorial Guinean', continent_id: 5},
{name: 'Eritrean', continent_id: 5},
{name: 'Estonian', continent_id: 3},
{name: 'Ethiopian', continent_id: 5},
{name: 'Fijian', continent_id: 1},
{name: 'Filipino', continent_id: 4},
{name: 'Finnish', continent_id: 3},
{name: 'French', continent_id: 3},
{name: 'Gabonese', continent_id: 5},
{name: 'Gambian', continent_id: 5},
{name: 'Georgian', continent_id: 3},
{name: 'German', continent_id: 3},
{name: 'Ghanaian', continent_id: 5},
{name: 'Greek', continent_id: 3},
{name: 'Grenadian', continent_id: 2},
{name: 'Guatemalan', continent_id: 2},
{name: 'Guinea-Bissauan', continent_id: 5},
{name: 'Guinean', continent_id: 5},
{name: 'Guyanese', continent_id: 0},
{name: 'Haitian', continent_id: 2},
{name: 'Herzegovinian', continent_id: 3},
{name: 'Honduran', continent_id: 2},
{name: 'Hungarian', continent_id: 3},
{name: 'I-Kiribati', continent_id: 1},
{name: 'Icelander', continent_id: 3},
{name: 'Indian', continent_id: 4},
{name: 'Indonesian', continent_id: 4},
{name: 'Iranian', continent_id: 4},
{name: 'Iraqi', continent_id: 4},
{name: 'Irish', continent_id: 3},
{name: 'Israeli', continent_id: 4},
{name: 'Italian', continent_id: 3},
{name: 'Ivorian', continent_id: 5},
{name: 'Jamaican', continent_id: 2},
{name: 'Japanese', continent_id: 4},
{name: 'Jordanian', continent_id: 4},
{name: 'Kazakhstani', continent_id: 4},
{name: 'Kenyan', continent_id: 5},
{name: 'Kittian and Nevisian', continent_id: 2},
{name: 'Kuwaiti', continent_id: 4},
{name: 'Kyrgyz', continent_id: 4},
{name: 'Laotian', continent_id: 4},
{name: 'Latvian', continent_id: 3},
{name: 'Lebanese', continent_id: 4},
{name: 'Liberian', continent_id: 5},
{name: 'Libyan', continent_id: 5},
{name: 'Liechtensteiner', continent_id: 3},
{name: 'Lithuanian', continent_id: 3},
{name: 'Luxembourger', continent_id: 3},
{name: 'Macedonian', continent_id: 3},
{name: 'Malagasy', continent_id: 5},
{name: 'Malawian', continent_id: 5},
{name: 'Malaysian', continent_id: 4},
{name: 'Maldivan', continent_id: 4},
{name: 'Malian', continent_id: 5},
{name: 'Maltese', continent_id: 3},
{name: 'Marshallese', continent_id: 1},
{name: 'Mauritanian', continent_id: 5},
{name: 'Mauritian', continent_id: 5},
{name: 'Mexican', continent_id: 2},
{name: 'Micronesian', continent_id: 1},
{name: 'Moldovan', continent_id: 3},
{name: 'Monacan', continent_id: 3},
{name: 'Mongolian', continent_id: 4},
{name: 'Moroccan', continent_id: 5},
{name: 'Mosotho', continent_id: 5},
{name: 'Motswana', continent_id: 5},
{name: 'Mozambican', continent_id: 5},
{name: 'Namibian', continent_id: 5},
{name: 'Nauruan', continent_id: 1},
{name: 'Nepalese', continent_id: 4},
{name: 'New Zealander', continent_id: 1},
{name: 'Nicaraguan', continent_id: 2},
{name: 'Nigerian', continent_id: 5},
{name: 'Nigerien', continent_id: 5},
{name: 'North Korean', continent_id: 4},
{name: 'Northern Irish', continent_id: 3},
{name: 'Norwegian', continent_id: 3},
{name: 'Omani', continent_id: 4},
{name: 'Pakistani', continent_id: 4},
{name: 'Palauan', continent_id: 1},
{name: 'Panamanian', continent_id: 2},
{name: 'Papua New Guinean', continent_id: 1},
{name: 'Paraguayan', continent_id: 0},
{name: 'Peruvian', continent_id: 0},
{name: 'Polish', continent_id: 3},
{name: 'Portuguese', continent_id: 3},
{name: 'Qatari', continent_id: 4},
{name: 'Romanian', continent_id: 3},
{name: 'Russian', continent_id: 4},
{name: 'Rwandan', continent_id: 5},
{name: 'Saint Lucian', continent_id: 2 },
{name: 'Salvadoran', continent_id: 2},
{name: 'Samoan', continent_id: 1},
{name: 'San Marinese', continent_id: 3},
{name: 'Sao Tomean', continent_id: 5},
{name: 'Saudi', continent_id: 4},
{name: 'Scottish', continent_id: 3},
{name: 'Senegalese', continent_id: 5},
{name: 'Serbian', continent_id: 3},
{name: 'Seychellois', continent_id: 5},
{name: 'Sierra Leonean', continent_id: 5},
{name: 'Singaporean', continent_id: 4},
{name: 'Slovakian', continent_id: 3},
{name: 'Slovenian', continent_id: 3},
{name: 'Solomon Islander', continent_id: 1},
{name: 'Somali', continent_id: 5},
{name: 'South African', continent_id: 5},
{name: 'South Korean', continent_id: 4},
{name: 'Spanish', continent_id: 3},
{name: 'Sri Lankan', continent_id: 4},
{name: 'Sudanese', continent_id: 5},
{name: 'Surinamer', continent_id: 0},
{name: 'Swazi', continent_id: 5},
{name: 'Swedish', continent_id: 3},
{name: 'Swiss', continent_id: 3},
{name: 'Syrian', continent_id: 4},
{name: 'Taiwanese', continent_id: 4},
{name: 'Tajik', continent_id: 4},
{name: 'Tanzanian', continent_id: 5},
{name: 'Thai', continent_id: 4},
{name: 'Togolese', continent_id: 5},
{name: 'Tongan', continent_id: 1},
{name: 'Trinidadian or Tobagonian', continent_id: 2},
{name: 'Tunisian', continent_id: 5},
{name: 'Turkish', continent_id: 4},
{name: 'Tuvaluan', continent_id: 1},
{name: 'Ugandan', continent_id: 5},
{name: 'Ukrainian', continent_id: 3},
{name: 'Uruguayan', continent_id: 0},
{name: 'Uzbekistani', continent_id: 4},
{name: 'Venezuelan', continent_id: 0},
{name: 'Vietnamese', continent_id: 4},
{name: 'Welsh', continent_id: 3},
{name: 'Yemenite', continent_id: 4},
{name: 'Zambian', continent_id: 5},
{name: 'Zimbabwean', continent_id: 5}])

Continent.create([
	{id: 0, name: 'South America'},
	{id: 1, name: 'Oceania'},
	{id: 2, name: 'North America'},
	{id: 3, name: 'Europe'},
	{id: 4, name: 'Asia'},
	{id: 5, name: 'Africa'},
	])