# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5475016eb67c916c977275108df77d794db1429fc932e47a92cf06fbc2b30108ca28485ee1d032c28252bfbc41abeb9af93df145bb2ea9ea1851286f5ca9d57

test:
  secret_key_base: e4acd385162c31e80e0585ef6bca2ae11997c0b44c98e6727c4731a17722ed1499bae9317cd3b0a36fd57617f62cf6a577d2c8c543cb5997ad1cf071e69f76b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
